# Generated by Django 6.1 on 2026-08-23 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0002_alter_vehicle_capacity"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripFuelRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Trip distance in kilometers",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_fuel_liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated fuel consumption in liters",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_fuel_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual fuel consumption in liters (NULL if telematics/refueling data unavailable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fuel_efficiency_km_per_liter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated fuel efficiency in km per liter",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "fuel_variance_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual fuel minus estimated fuel in liters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fuel_variance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage variance: ((Actual - Estimated) / Estimated) * 100",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Driver/Dispatcher Entry"),
                            ("TELEMATICS", "Vehicle Telematics Sensor"),
                            ("FUEL_STATION", "Fuel Station Refueling Record"),
                            ("IMPORTED", "Imported Batch Log"),
                            ("CALCULATED", "System Calculated Baseline"),
                        ],
                        default="MANUAL",
                        max_length=30,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_fuel_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_record",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_records",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Fuel Record",
                "verbose_name_plural": "Trip Fuel Records",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "recorded_at"],
                        name="analytics_t_vehicle_90f3d0_idx",
                    ),
                    models.Index(
                        fields=["driver", "recorded_at"],
                        name="analytics_t_driver__65676d_idx",
                    ),
                ],
            },
        ),
    ]
