# Generated by Django 6.1 on 2026-08-23 19:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "period",
                    models.CharField(
                        db_index=True, help_text="Format YYYY-MM", max_length=7
                    ),
                ),
                ("completed_trips", models.IntegerField(default=0)),
                ("on_time_trips", models.IntegerField(default=0)),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage 0.00 - 100.00",
                        max_digits=5,
                    ),
                ),
                ("incident_count", models.IntegerField(default=0)),
                (
                    "incident_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage 0.00 - 100.00",
                        max_digits=5,
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_fuel_liters",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fuel_efficiency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="km per Liter",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1.00 - 5.00",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporter Performance",
                "verbose_name_plural": "Transporter Performances",
                "ordering": ["-year", "-month", "transporter"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transporter", "year", "month"),
                        name="unique_transporter_monthly_performance",
                    )
                ],
            },
        ),
    ]
