# Generated by Django 6.1 on 2026-08-23 17:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional client/device unique identifier for duplicate event prevention foundation.",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Spatial PostGIS WGS84 Point(longitude, latitude).",
                        srid=4326,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Geographic latitude value in range [-90, 90].",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Geographic longitude value in range [-180, 180].",
                        max_digits=9,
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Speed in km/h.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Heading in degrees [0, 360).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp generated on the GPS device.",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the server received the event.",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "-recorded_at"],
                        name="tracking_tr_shipmen_378e69_idx",
                    ),
                    models.Index(
                        fields=["driver", "-recorded_at"],
                        name="tracking_tr_driver__4847ab_idx",
                    ),
                    models.Index(
                        fields=["-recorded_at"], name="tracking_tr_recorde_80e0dd_idx"
                    ),
                ],
            },
        ),
    ]
