# Generated by Django 6.1 on 2026-08-23 18:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="OSRM",
                        help_text="Routing provider: OSRM, Geodesic, etc.",
                        max_length=50,
                    ),
                ),
                ("provider_route_id", models.CharField(blank=True, max_length=255)),
                ("origin_city", models.CharField(db_index=True, max_length=100)),
                ("destination_city", models.CharField(db_index=True, max_length=100)),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total route distance in kilometers",
                        max_digits=10,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Estimated travel duration in minutes"
                    ),
                ),
                (
                    "estimated_fuel_liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated fuel consumption in liters",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_fuel_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated total fuel cost in ETB",
                        max_digits=12,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Security/corridor risk score between 0.00 (safe) and 1.00 (severe risk)",
                        max_digits=5,
                    ),
                ),
                (
                    "optimization_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Weighted multi-attribute cost score (lower is better)",
                        max_digits=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ROUTE_ACTIVE", "Active Route"),
                            ("REROUTE_PROPOSED", "Reroute Proposed"),
                            ("REROUTE_ACCEPTED", "Reroute Accepted"),
                            ("REROUTE_REJECTED", "Reroute Rejected"),
                            ("INACTIVE", "Inactive / Historical"),
                        ],
                        db_index=True,
                        default="ROUTE_ACTIVE",
                        max_length=30,
                    ),
                ),
                ("is_recommended", models.BooleanField(db_index=True, default=False)),
                (
                    "algorithm_version",
                    models.CharField(default="routing-v1", max_length=50),
                ),
                (
                    "geometry_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoJSON or coordinate list representation",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["optimization_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteLeg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Leg sequence number (1, 2, 3...)"
                    ),
                ),
                (
                    "start_point",
                    models.CharField(
                        help_text="Leg origin waypoint/city", max_length=255
                    ),
                ),
                (
                    "end_point",
                    models.CharField(
                        help_text="Leg destination waypoint/city", max_length=255
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "estimated_fuel_liters",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("road_condition", models.CharField(default="GOOD", max_length=50)),
                (
                    "security_risk_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.10"), max_digits=5
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="routing.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Leg",
                "verbose_name_plural": "Route Legs",
                "ordering": ["route", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["shipment", "status"], name="routing_rou_shipmen_353063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["shipment", "is_recommended"],
                name="routing_rou_shipmen_5516b2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routeleg",
            unique_together={("route", "sequence")},
        ),
    ]
