# Generated by Django 6.1 on 2026-08-23 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary title of the freight load",
                        max_length=255,
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(
                        db_index=True,
                        help_text="Origin city (e.g., Djibouti Port, Modjo, Addis Ababa)",
                        max_length=100,
                    ),
                ),
                (
                    "origin_address",
                    models.TextField(
                        blank=True, help_text="Detailed pickup location address"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        db_index=True,
                        help_text="Destination city (e.g., Hawassa, Mekelle, Dire Dawa)",
                        max_length=100,
                    ),
                ),
                (
                    "destination_address",
                    models.TextField(
                        blank=True, help_text="Detailed delivery location address"
                    ),
                ),
                (
                    "cargo_type",
                    models.CharField(
                        choices=[
                            ("GENERAL_CARGO", "General Cargo"),
                            ("DRY_BULK", "Dry Bulk"),
                            ("LIQUID_BULK", "Liquid Bulk"),
                            ("CONTAINERIZED", "Containerized"),
                            ("REFRIGERATED", "Refrigerated / Perishable"),
                            ("HAZARDOUS", "Hazardous Material"),
                            ("HEAVY_MACHINERY", "Heavy Machinery / Out of Gauge"),
                        ],
                        db_index=True,
                        default="GENERAL_CARGO",
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in metric tons",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume in cubic meters",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "pickup_window_start",
                    models.DateTimeField(
                        db_index=True, help_text="Earliest pickup date & time"
                    ),
                ),
                (
                    "pickup_window_end",
                    models.DateTimeField(help_text="Latest pickup date & time"),
                ),
                (
                    "delivery_window_start",
                    models.DateTimeField(
                        blank=True, help_text="Earliest delivery date & time", null=True
                    ),
                ),
                (
                    "delivery_window_end",
                    models.DateTimeField(
                        blank=True, help_text="Latest delivery date & time", null=True
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Temperature control, tarpaulin, handling instructions, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Load",
                "verbose_name_plural": "Loads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "status",
                            "origin_city",
                            "destination_city",
                            "cargo_type",
                        ],
                        name="marketplace_status_dc8344_idx",
                    ),
                    models.Index(
                        fields=["shipper", "status"],
                        name="marketplace_shipper_7cd215_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weight__gt", 0)),
                        name="load_weight_positive_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("volume__isnull", True), ("volume__gt", 0), _connector="OR"
                        ),
                        name="load_volume_positive_check",
                    ),
                ],
            },
        ),
    ]
