# Generated by Django 6.1 on 2026-08-23 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SHIPMENT_DEPARTED", "Shipment Departed"),
                            ("SHIPMENT_CUSTOMS_CLEARED", "Shipment Customs Cleared"),
                            ("SHIPMENT_ARRIVED", "Shipment Arrived Destination"),
                            ("SHIPMENT_DELIVERED", "Shipment Delivered"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PAYOUT_PROCESSED", "Payout Processed"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("DISPUTE_CREATED", "Dispute Created"),
                            ("DISPUTE_RESOLVED", "Dispute Resolved"),
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App Notification"),
                            ("EMAIL", "Email Notification"),
                            ("SMS", "SMS Notification"),
                            ("PUSH", "Push Notification"),
                        ],
                        db_index=True,
                        default="IN_APP",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=100)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique event key to prevent duplicate notifications",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read"],
                        name="notificatio_recipie_6e3964_idx",
                    ),
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_e285de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SHIPMENT_DEPARTED", "Shipment Departed"),
                            ("SHIPMENT_CUSTOMS_CLEARED", "Shipment Customs Cleared"),
                            ("SHIPMENT_ARRIVED", "Shipment Arrived Destination"),
                            ("SHIPMENT_DELIVERED", "Shipment Delivered"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PAYOUT_PROCESSED", "Payout Processed"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("DISPUTE_CREATED", "Dispute Created"),
                            ("DISPUTE_RESOLVED", "Dispute Resolved"),
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App Notification"),
                            ("EMAIL", "Email Notification"),
                            ("SMS", "SMS Notification"),
                            ("PUSH", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "notification_type", "channel"),
                        name="unique_user_notification_type_channel",
                    )
                ],
            },
        ),
    ]
