# Generated by Django 6.1 on 2026-08-23 18:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_alter_load_status_bid"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("origin_city", models.CharField(db_index=True, max_length=100)),
                ("destination_city", models.CharField(db_index=True, max_length=100)),
                (
                    "agreed_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Agreed locked freight rate in ETB",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="ETB", max_length=10)),
                ("valid_from", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "divergence_threshold_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Allowed spot rate divergence percentage before warning flag",
                        max_digits=5,
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter_contract_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Rate",
                "verbose_name_plural": "Contract Rates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base rate calculation before dynamic adjustments",
                        max_digits=12,
                    ),
                ),
                (
                    "demand_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Demand/capacity ratio multiplier",
                        max_digits=5,
                    ),
                ),
                (
                    "fuel_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Fuel price index multiplier",
                        max_digits=5,
                    ),
                ),
                (
                    "congestion_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Corridor congestion level multiplier",
                        max_digits=5,
                    ),
                ),
                (
                    "calculated_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price output before floor/ceiling clamping",
                        max_digits=12,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final price output after floor/ceiling bounds",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="ETB", max_length=10)),
                (
                    "pricing_method",
                    models.CharField(
                        db_index=True,
                        default="RULE_BASED",
                        help_text="Method tag: RULE_BASED, ML, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        default="pricing-v1",
                        help_text="Pricing algorithm version identifier",
                        max_length=50,
                    ),
                ),
                ("valid_from", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "divergence_warning",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged True if spot rate diverges significantly from locked contract rate",
                    ),
                ),
                ("divergence_notes", models.TextField(blank=True)),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_quotes",
                        to="marketplace.load",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_quotes",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Quote",
                "verbose_name_plural": "Price Quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Exact JSON snapshot of all calculation inputs (base_rate, demand, fuel, congestion, floor, ceiling)",
                    ),
                ),
                (
                    "output_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Exact JSON snapshot of calculation results and multipliers",
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=50)),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("calculation_reason", models.TextField(blank=True)),
                (
                    "price_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="pricing.pricequote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Audit",
                "verbose_name_plural": "Pricing Audits",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pricequote",
            index=models.Index(
                fields=["load", "-created_at"], name="pricing_pri_load_id_0e09f9_idx"
            ),
        ),
    ]
