# Generated by Django 6.1 on 2026-08-23 18:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETAPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "predicted_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp when calculation was performed",
                    ),
                ),
                (
                    "estimated_arrival",
                    models.DateTimeField(
                        db_index=True, help_text="Predicted arrival date & time"
                    ),
                ),
                (
                    "remaining_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated remaining distance in kilometers",
                        max_digits=10,
                    ),
                ),
                (
                    "expected_speed_kmh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected vehicle travel speed in km/h",
                        max_digits=5,
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total accumulated delay in minutes (check-ins, incidents, checkpoints)",
                    ),
                ),
                (
                    "prediction_method",
                    models.CharField(
                        db_index=True,
                        default="RULE_BASED",
                        help_text="Method tag: RULE_BASED, ML, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        default="eta-v1",
                        help_text="Algorithm identifier version",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.85"),
                        help_text="Prediction confidence score between 0.00 and 1.00",
                        max_digits=5,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eta_predictions",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETA Prediction",
                "verbose_name_plural": "ETA Predictions",
                "ordering": ["-predicted_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "-predicted_at"],
                        name="eta_etapred_shipmen_591ee2_idx",
                    )
                ],
            },
        ),
    ]
