# Generated by Django 6.1 on 2026-08-23 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifier of the user, system process, or client performing the action",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("VERIFY", "Verify"),
                            ("REJECT", "Reject"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        help_text="Action type (e.g. CREATE, UPDATE, DELETE, VERIFY)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Target resource type (e.g. User, Load, Shipment)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Target resource primary key / UUID identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured contextual metadata (excluding sensitive credentials/keys)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "action"],
                        name="core_auditl_actor_i_7840a5_idx",
                    ),
                ],
            },
        ),
    ]
