# Generated by Django 6.1 on 2026-08-23 14:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        help_text="Vehicle license plate / registration number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("LIGHT_TRUCK", "Light Truck"),
                            ("MEDIUM_TRUCK", "Medium Truck"),
                            ("HEAVY_TRUCK", "Heavy Truck"),
                            ("TRACTOR_TRUCK", "Tractor Truck"),
                            ("TRAILER", "Trailer"),
                            ("TANKER", "Tanker"),
                            ("REFRIGERATED_TRUCK", "Refrigerated Truck"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="HEAVY_TRUCK",
                        max_length=30,
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum carrying payload capacity",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(
                        choices=[
                            ("TON", "Ton"),
                            ("KG", "Kilogram"),
                            ("CBM", "Cubic Meter"),
                        ],
                        default="TON",
                        max_length=10,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("ELECTRIC", "Electric"),
                            ("HYBRID", "Hybrid"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="DIESEL",
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_MAINTENANCE", "In Maintenance"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="profiles.transporterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INSURANCE", "Insurance Policy"),
                            ("ROADWORTHINESS", "Roadworthiness Certificate"),
                            ("REGISTRATION", "Vehicle Registration Ownership"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Document",
                "verbose_name_plural": "Vehicle Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["transporter", "status"], name="fleet_vehic_transpo_129199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_type", "status"], name="fleet_vehic_vehicle_3796c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="vehicle_capacity_positive_check",
            ),
        ),
    ]
