# Generated by Django 6.1 on 2026-08-23 17:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_alter_load_status_bid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Rank order in shortlist (1=top match)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weighted total match score (0.00 - 100.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "cost_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "reliability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "fuel_efficiency_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("70.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "proximity_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "availability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explainable breakdown of factors contributing to recommendation",
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        default="v1",
                        help_text="Matching engine version tag",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(db_index=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether recommendation is part of active shortlist",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_recommendations",
                        to="marketplace.load",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Recommendation",
                "verbose_name_plural": "Match Recommendations",
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["load", "is_active", "rank"],
                        name="matching_ma_load_id_0044b6_idx",
                    ),
                    models.Index(
                        fields=["transporter", "is_active"],
                        name="matching_ma_transpo_273c5f_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rank__gt", 0)),
                        name="match_rank_positive_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total_score__gte", 0), ("total_score__lte", 100)
                        ),
                        name="match_total_score_range_check",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("load", "transporter"),
                        name="unique_active_match_recommendation_per_transporter_and_load",
                    ),
                ],
            },
        ),
    ]
