# Generated by Django 6.1 on 2026-08-23 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomsDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("COMMERCIAL_INVOICE", "Commercial Invoice"),
                            ("PACKING_LIST", "Packing List"),
                            ("BILL_OF_LADING", "Bill of Lading"),
                            ("CERTIFICATE_OF_ORIGIN", "Certificate of Origin"),
                            ("OTHER", "Other Supporting Document"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="customs_documents/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Official invoice or document reference number",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Declared financial value on document in ETB",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Declared item quantity",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "clearance_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Clearance"),
                            ("UNDER_REVIEW", "Under Customs Review"),
                            ("CLEARED", "Customs Cleared"),
                            ("REJECTED", "Clearance Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Validation"),
                            ("PASSED", "Validation Passed"),
                            ("FAILED", "Validation Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "validation_notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation result errors or warnings breakdown",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by customs staff upon rejection",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_customs_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs_documents",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_customs_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customs Document",
                "verbose_name_plural": "Customs Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "document_type"],
                        name="customs_cus_shipmen_6667fc_idx",
                    ),
                    models.Index(
                        fields=["shipment", "clearance_status"],
                        name="customs_cus_shipmen_871425_idx",
                    ),
                ],
            },
        ),
    ]
