# Generated by Django 6.1 on 2026-08-23 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSyncEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUIDv4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "client_event_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Unique client-generated event UUID for idempotency",
                        unique=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of mobile device",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WAYPOINT_CHECKIN", "Waypoint Check-In"),
                            ("INCIDENT_REPORT", "Incident Report"),
                            ("TRACKING_EVENT", "GPS Tracking Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text="Target entity type, e.g. shipment",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Target entity UUID, e.g. shipment_id",
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Event payload data dictionary"
                    ),
                ),
                (
                    "client_created_at",
                    models.DateTimeField(
                        help_text="Timestamp when action was performed on device"
                    ),
                ),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SYNCING", "Syncing"),
                            ("SYNCED", "Synced"),
                            ("FAILED", "Failed"),
                            ("CONFLICT", "Conflict"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                (
                    "server_entity_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of server domain entity created/updated",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Sync Event",
                "verbose_name_plural": "Offline Sync Events",
                "ordering": ["-client_created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="synchroniza_user_id_44a40f_idx"
                    ),
                    models.Index(
                        fields=["event_type", "entity_id"],
                        name="synchroniza_event_t_911a78_idx",
                    ),
                ],
            },
        ),
    ]
